// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: src/main/resources/proto/training.proto

package com.tnsilver.protobuf;


@SuppressWarnings("all")
public class TrainingProtosValidator {
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.Courses.class)) return new CoursesValidator();
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.Students.class)) return new StudentsValidator();
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.PhoneNumbers.class)) return new PhoneNumbersValidator();
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.Course.class)) return new CourseValidator();
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.Student.class)) return new StudentValidator();
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.Error.class)) return new ErrorValidator();
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.Student.PhoneNumber.class)) return new Student_PhoneNumberValidator();
		if (clazz.equals(com.tnsilver.protobuf.TrainingProtos.Error.FieldError.class)) return new Error_FieldErrorValidator();
		return null;
	}


/**
	 * Validates {@code Courses} protobuf objects.
	 */
	public static class CoursesValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.Courses> {
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.Courses proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getCoursesList(), item -> {
				
			// Validate courses
			if (true) index.validatorFor(item).assertValid(item);
			});
	
	
	}
}
/**
	 * Validates {@code Students} protobuf objects.
	 */
	public static class StudentsValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.Students> {
		
	
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.Students proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for CourseId

	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getStudentsList(), item -> {
				
			// Validate students
			if (true) index.validatorFor(item).assertValid(item);
			});
	
	
	}
}
/**
	 * Validates {@code PhoneNumbers} protobuf objects.
	 */
	public static class PhoneNumbersValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.PhoneNumbers> {
		
	
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.PhoneNumbers proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Id

	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getPhoneList(), item -> {
				
			// Validate phone
			if (true) index.validatorFor(item).assertValid(item);
			});
	
	
	}
}
/**
	 * Validates {@code Course} protobuf objects.
	 */
	public static class CourseValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.Course> {
		
	
		
	
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.Course proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Id

	
			io.envoyproxy.pgv.StringValidation.minLength(".protobuf.Course.course_name", proto.getCourseName(), 5);
			io.envoyproxy.pgv.StringValidation.maxLength(".protobuf.Course.course_name", proto.getCourseName(), 30);
	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getStudentList(), item -> {
				
			// Validate student
			if (true) index.validatorFor(item).assertValid(item);
			});
	
	
	}
}
/**
	 * Validates {@code Student} protobuf objects.
	 */
	public static class StudentValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.Student> {
		
	
		
	
		
	
		
	
		
	
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.Student proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Id

	
			io.envoyproxy.pgv.StringValidation.minLength(".protobuf.Student.first_name", proto.getFirstName(), 2);
			io.envoyproxy.pgv.StringValidation.maxLength(".protobuf.Student.first_name", proto.getFirstName(), 30);
	
			io.envoyproxy.pgv.StringValidation.minLength(".protobuf.Student.last_name", proto.getLastName(), 2);
			io.envoyproxy.pgv.StringValidation.maxLength(".protobuf.Student.last_name", proto.getLastName(), 30);
	
			io.envoyproxy.pgv.StringValidation.email(".protobuf.Student.email", proto.getEmail());
	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getPhoneList(), item -> {
				
			// Validate phone
			if (true) index.validatorFor(item).assertValid(item);
			});
	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getCourseRefsList(), item -> {
				// no validation rules for CourseRefs

			});
	
	
	}
}
/**
	 * Validates {@code Error} protobuf objects.
	 */
	public static class ErrorValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.Error> {
		
	
		
	
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.Error proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getDataList(), item -> {
				
			// Validate data
			if (true) index.validatorFor(item).assertValid(item);
			});
	// no validation rules for Error

	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getFieldErrorsList(), item -> {
				
			// Validate fieldErrors
			if (true) index.validatorFor(item).assertValid(item);
			});
	
	
	}
}
/**
	 * Validates {@code Student_PhoneNumber} protobuf objects.
	 */
	public static class Student_PhoneNumberValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.Student.PhoneNumber> {
		
	
		
		com.google.re2j.Pattern NUMBER__PATTERN = com.google.re2j.Pattern.compile("[+\\d]?[0-9]{6,13}");
	
		
		private final com.tnsilver.protobuf.TrainingProtos.Student.PhoneType[] TYPE__IN = new com.tnsilver.protobuf.TrainingProtos.Student.PhoneType[]{
			com.tnsilver.protobuf.TrainingProtos.Student.PhoneType.forNumber(1),
			com.tnsilver.protobuf.TrainingProtos.Student.PhoneType.forNumber(2),
			com.tnsilver.protobuf.TrainingProtos.Student.PhoneType.forNumber(3),
			com.tnsilver.protobuf.TrainingProtos.Student.PhoneType.forNumber(4),
		};
	
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.Student.PhoneNumber proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Id

	
			io.envoyproxy.pgv.StringValidation.pattern(".protobuf.Student.PhoneNumber.number", proto.getNumber(), NUMBER__PATTERN);
	
			io.envoyproxy.pgv.CollectiveValidation.in(".protobuf.Student.PhoneNumber.type", proto.getType(), TYPE__IN);
	// no validation rules for StudentRef

	
	
	}
}
/**
	 * Validates {@code Error_FieldError} protobuf objects.
	 */
	public static class Error_FieldErrorValidator implements io.envoyproxy.pgv.ValidatorImpl<com.tnsilver.protobuf.TrainingProtos.Error.FieldError> {
		
	
		
	
	
	

	public void assertValid(com.tnsilver.protobuf.TrainingProtos.Error.FieldError proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Name

	// no validation rules for Status

	
	
	}
}
}

